apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.database.secretArn }}
        objectType: secretsmanager
        jmesPath:
          - path: username
            objectAlias: username
          - path: password
            objectAlias: password
          - path: host
            objectAlias: host
          - path: dbname
            objectAlias: dbname
  secretObjects:
    - secretName: {{ .Values.database.secretName }}
      type: Opaque
      data:
        - objectName: username
          key: username
        - objectName: password
          key: password
        - objectName: host
          key: host
        - objectName: dbname
          key: dbname
